# SPDX-FileCopyrightText: 2024 Osnabrück University of Applied Sciences
# SPDX-FileContributor: Andreas Schliebitz
# SPDX-FileContributor: Henri Graf
# SPDX-FileContributor: Jonas Tüpker
# SPDX-FileContributor: Lukas Hesse
# SPDX-FileContributor: Maik Fruhner
# SPDX-FileContributor: Prof. Dr.-Ing. Heiko Tapken
# SPDX-FileContributor: Tobias Wamhof
#
# SPDX-License-Identifier: MIT

edc.vault=vault.properties
edc.aws.access.key=usernamePlatform
edc.aws.secret.access.key=passwordPlatform

usernamePlatform=MINIO_ROOT_USER
passwordPlatform=MINIO_ROOT_PASSWORD