# SPDX-FileCopyrightText: 2024 University of Applied Sciences Osnabrück
# SPDX-FileContributor: Andreas Schliebitz
# SPDX-FileContributor: Henri Graf
# SPDX-FileContributor: Jonas Tüpker
# SPDX-FileContributor: Lukas Hesse
# SPDX-FileContributor: Maik Fruhner
# SPDX-FileContributor: Prof. Dr.-Ing. Heiko Tapken
# SPDX-FileContributor: Tobias Wamhof
#
# SPDX-License-Identifier: AGPL-3.0-or-later

ARG JUPYTERHUB_VERSION="5"

FROM jupyterhub/jupyterhub:${JUPYTERHUB_VERSION}

COPY requirements.txt .
RUN python3 -m pip install --no-cache-dir -r requirements.txt

COPY docker-entrypoint.dev.sh .
RUN chmod +x ./docker-entrypoint.dev.sh

ENTRYPOINT ["/bin/bash", "./docker-entrypoint.dev.sh"]
